# Generated by Django 5.1 on 2024-09-07 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, message='Email must be at least 5 characters long.')])),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Username must be at least 4 characters long.')])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.')])),
                ('security', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Security question answer must be at least 3 characters long.')])),
            ],
        ),
    ]
