# Generated by Django 5.1 on 2024-09-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_accounts_table_email_cart_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
