# Generated by Django 5.1 on 2024-09-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_cart_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
