# Generated by Django 5.1 on 2024-09-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_cart_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_image',
        ),
    ]
