# Generated by Django 5.1 on 2024-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_remove_cart_image_remove_cart_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_table',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
